apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: monsteralab-auth
spec:
  protocol: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monsteralab-auth
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monsteralab-auth
  name: monsteralab-auth
spec:
  selector:
    app: monsteralab-auth
  ports:
    - name: monsteralab-auth-port
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monsteralab-auth
  labels:
    app: monsteralab-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monsteralab-auth
  template:
    metadata:
      name: monsteralab-auth
      labels:
        app: monsteralab-auth
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: monsteralab-auth
          image: guido233/monsteralab-auth:a19f7bbbc7dcf2253b0d2ce72c1c51c5aa77be68
          env:
            - name: SERVICE_NAME
              value: monsteralab-auth
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: dot-env-secret
          ports:
            - containerPort: 3000
