#apiVersion: v1
#kind: Service
#metadata:
#  name: monsteralab-auth-service
#spec:
#  selector:
#    app: monsteralab-auth
#  ports:
#    - name: monsteralab-auth-port
#      port: 80
#      targetPort: auth-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monsteralab-auth
  labels:
    app: monsteralab-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monsteralab-auth
  template:
    metadata:
      name: monsteralab-auth
      labels:
        app: monsteralab-auth
      annotations:
        'consul.hashicorp.com/connect-inject': 'false'
    spec:
      containers:
        - name: monsteralab-auth
          image: guido233/monsteralab-auth:a19f7bbbc7dcf2253b0d2ce72c1c51c5aa77be68
          ports:
            - containerPort: 3000
              name: auth-port
          env:
          - name: CONSUL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SERVICE_NAME
            value: "monsteralab-auth"
          readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 3
              resources:
                limits:
                  cpu: "0.1"
                  memory: 100Mi
