global:
  name: consul
  datacenter: ms1
  tls:
    enabled: true
server:
  replicas: 3
ui:
  enabled: true
  service:
    type: NodePort
connectInject:
  enabled: true
controller:
  enabled: true
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.4.0"
  managedGatewayClass:
    enabled: true
    serviceType: LoadBalancer
